# .github/workflows/test.yml

name: continuous-integration

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - run: invoke build.install-package
      - run: invoke test.format
      - run: invoke integration.clean
      - run: invoke integration.version
      - run: invoke integration.initialize
      - run: invoke unit.pytest
      - run: invoke test.security
      - run: invoke integration.query
      - run: invoke integration.write-policy
      - run: invoke build.uninstall-package

  python-version:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: true
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - run: invoke build.install-package
      - run: invoke integration.clean
      - run: invoke integration.version
      - run: invoke integration.initialize
      - run: invoke unit.pytest
      - run: invoke integration.query
      - run: invoke integration.write-policy
      - run: invoke build.uninstall-package
